source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
      
inhibit_all_warnings!
      
def common_pods
  pod 'Sourcery'
  pod 'ObjectMapper'
end
      
target 'MeetupXExample' do
  use_frameworks!
  common_pods
end
      
