name: MeetupXExample
options:
  bundleIdPrefix: com.agexample

targets:
  MeetupXExample:
    type: application
    platform: iOS
    deploymentTarget: 12.1
    sources: [/Users/karimebrahem/Desktop/MeetupXExample/TestProject]
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

